apiVersion: v1 
kind: Pod 
metadata:
  name: web-pod
  labels: 
    app: web-pod
spec:
  containers:
  - name: web-pod
    image: 931588/otus-homework:1-nginx
    volumeMounts:
      - name: app
        mountPath: /app
  initContainers:
  - name: init-web
    image: busybox:1.28
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
      - name: app
        mountPath: /app
  volumes:
  - name: app
    emptyDir: {}